language: c
compiler: gcc
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.sonar/cache

env:
  global:
    - MY_PV=3.0.0_alpha1

install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - sudo apt-get install -y gettext libc6-dbg libpam-ck-connector libck-connector0 libck-connector-dev libefl libefl-dbg libefl-dev python3-pip libpam0g-dev
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson==0.44
  - mkdir .bin
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .bin/ninja-linux.zip
  - unzip .bin/ninja-linux.zip -d .bin

before_script:
  - export PATH=$PATH:$PWD/.bin

jobs:
  include:
    - stage: Test builds
    - env: OPTS="-Dconsolekit=false"
    - env: OPTS="-Dpam=false"
    - env: OPTS="-Dconsolekit=false -Dpam=false"
    - stage: Sonar Cloud
      env:
        - SONAR="build-wrapper-linux-x86-64 --out-dir bw-output"
      addons:
        sonarcloud:
          organization: obsidian-studiosinc-github
          token:
            secure: q5YHyZC+bDJqd5UEnedOc4H1qzdBVTVyez30AJF/+ZewXnc/Hp5SOsj5GKgehoFpZWYLsS9mVxLG3eGFTvELlWx8gQL0iwadwD1Jph7nzT+cX0oDJYt3UdPzZvZxtkogQIhEdco5bWDny3SsCqpa8bjWnEiB/6gi5elSRw5Yi68JmEeqcMvgQzmtAx8wFvD1a2SeEFo/ctNMJYA2UszMLrsGSZtbhysN4xgKKKOygWRefH+B0UvKybVREVYYd0kuJ2F0JlfLW9BoBhw1dWhd9yTRp/++Phgc6a5mhdMCQk6xXAVsz3EMRjNbCITFkUd5hRI+9ye5VlL5WheJ2zwqkVkhSulsJkzyGlkuJbxYgarfzktBImhKlVrIggXtsEKikTZEgokUpl0Kee9/AbcYmonTJqhSN87XNcy5cH7q7+pUdJui+wov8NZIRDMU/S7sDB2UpeqjSILoQ7cyWLf/cFglQ2aYMcTvn1JIiuvT3boVqMQqWtphyHj4cQfzU6py6bfHAlugFKDdpu0t6xIZnbZHZGz+2uLcQg4mqGeqM0RGA5b+Pi++cbu+BdVzJScp0CQ8ibQxzAgyJxzfGZT7Z2RH5kzsJIpbbfAU7V2cznHMVwpgbbcJmOsrlkWp8LjxDZIy0ftnIA0eSKfeJ3cr6OPFmWtcYDu9Fw7TW4q0tu4=

script:
  - meson --prefix /usr ${OPTS} . build
  - ${SONAR} .bin/ninja -C build
  - if [ "${SONAR}" ]; then find . -name '*.gcno' -exec sh -c 'gcov -b {} -o $(dirname {})' \;; fi
  - if [ "${SONAR}" ]; then sonar-scanner; fi

notifications:
  email: false
